### ISSUE TITLE
Create CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by payaldutta** [Learn-Write-Repeat/Linux#1]
I want to create a code of conduct file for those who are new to open source. @HemantTomar Can I work on this?

**Comment by HemantTomar** [comment]
Hi Payal ,
Yes you can .

Thanks
Hemant

**Comment by payaldutta** [comment]
@HemantTomar Do assign me this so that I can make a PR for this.
Thank You.

**Comment by HemantTomar** [comment]
Done
